---
settings:
  name: HCI
  downlevel: true
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - version-number: '1.9'
    url: "/hci19"
  - version-number: '1.10'
    url: "/hci"
  - version-number: '1.8'
    url: "/hci18"
  langs: es-es,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,fr-fr,it-it
sidebar:
  entries:
  - title: Documentación de NetApp HCI
    url: "/index.html"
  - title: Soluciones NetApp HCI
    url: "/docs/hci_solutions_index.html"
  - title: Notas de la versión
    entries:
    - title: Novedades en NetApp HCI
      url: "/docs/rn_whatsnew.html"
    - title: Información adicional sobre la versión
      url: "/docs/rn_relatedrn.html"
  - title: Conceptos
    entries:
    - title: Información general del producto
      url: "/docs/concept_hci_product_overview.html"
    - title: Cuentas
      url: "/docs/concept_cg_hci_accounts.html"
    - title: Protección de datos
      url: "/docs/concept_hci_dataprotection.html"
    - title: De clúster
      url: "/docs/concept_hci_clusters.html"
    - title: Nodos
      url: "/docs/concept_hci_nodes.html"
    - title: Reducida
      entries:
      - title: Modo de mantenimiento
        url: "/docs/concept_hci_storage_maintenance_mode.html"
      - title: Volúmenes
        url: "/docs/concept_hci_volumes.html"
      - title: Los grupos de acceso de volúmenes
        url: "/docs/concept_hci_volume_access_groups.html"
      - title: Iniciadores
        url: "/docs/concept_hci_initiators.html"
      - title: Dominios de protección personalizados
        url: "/docs/concept_hcc_custom_protection_domains.html"
    - title: Licencia
      url: "/docs/concept_cg_hci_licensing.html"
    - title: Máximos de configuración del control del cloud híbrido de NetApp
      url: "/docs/reference_hcc_config_maximums.html"
    - title: Seguridad
      url: "/docs/concept_cg_hci_security.html"
    - title: Rendimiento
      url: "/docs/concept_hci_performance.html"
  - title: Requisitos y tareas previas a la implementación
    entries:
    - title: Requisitos para la instalación de NetApp HCI
      url: "/docs/hci_prereqs_overview.html"
    - title: Requisitos del nodo de gestión
      url: "/docs/hci_prereqs_management_node.html"
    - title: Requisitos de puerto de red
      url: "/docs/hci_prereqs_required_network_ports.html"
    - title: Requisitos de switch y red
      url: "/docs/hci_prereqs_network_switch.html"
    - title: Requisitos de cables de red
      url: "/docs/hci_prereqs_network_cables.html"
    - title: Requisitos de dirección IP
      url: "/docs/hci_prereqs_ip_address.html"
    - title: Configuración de red
      entries:
      - title: Información general sobre las opciones de configuración de red
        url: "/docs/hci_prereqs_network_configuration.html"
      - title: Opción de configuración de red A
        url: "/docs/hci_prereqs_network_configuration_option_A.html"
      - title: Opción de configuración de red B
        url: "/docs/hci_prereqs_network_configuration_option_B.html"
      - title: Opción de configuración de red C
        url: "/docs/hci_prereqs_network_configuration_option_C.html"
    - title: Requisitos de DNS y de control del tiempo
      url: "/docs/hci_prereqs_timekeeping.html"
    - title: Requisitos ambientales
      url: "/docs/hci_prereqs_environmental.html"
    - title: Dominios de protección
      url: "/docs/hci_prereqs_protection_domains.html"
    - title: Requisitos de recursos de nodo de observación para clústeres de almacenamiento
        de dos nodos
      url: "/docs/hci_prereqs_witness_nodes.html"
  - title: Empiece a usar NetApp HCI
    entries:
    - title: Información general sobre la instalación y la puesta en marcha de NetApp
        HCI
      url: "/docs/task_hci_getstarted.html"
    - title: Instale el hardware H-Series
      url: "/docs/task_hci_installhw.html"
    - title: Configure LACP para alcanzar un rendimiento de almacenamiento óptimo
      url: "/docs/hci_prereqs_LACP_configuration.html"
    - title: Validar su entorno con Active IQ Config Advisor
      url: "/docs/hci_prereqs_task_validate_config_advisor.html"
    - title: Configure IPMI para cada nodo
      url: "/docs/hci_prereqs_final_prep.html"
  - title: Ponga en marcha NetApp HCI
    entries:
    - title: Acceda al motor de implementación de NetApp
      entries:
      - title: Información general de las opciones de acceso del motor de implementación
          de NetApp
        url: "/docs/concept_nde_access_overview.html"
      - title: Acceda al motor de implementación de NetApp en entornos sin DHCP
        url: "/docs/task_nde_access_no_dhcp.html"
      - title: Acceda al motor de implementación de NetApp en entornos con DHCP
        url: "/docs/task_nde_access_dhcp.html"
      - title: Asignar manualmente todas las direcciones IP para acceder al motor
          de implementación de NetApp
        url: "/docs/task_nde_access_manual_ip.html"
    - title: Inicie la implementación
      url: "/docs/task_nde_start_deployment.html"
    - title: Importe un perfil de instalación
      url: "/docs/task_nde_import_installation_profile.html"
    - title: Configure VMware vSphere
      entries:
      - title: Información general de la configuración de vSphere
        url: "/docs/concept_nde_config_vsphere_overview.html"
      - title: Configurar un nuevo entorno de VMware vSphere
        url: "/docs/task_nde_configure_new_vsphere.html"
      - title: Únase a una puesta en marcha de VMware vSphere existente
        url: "/docs/task_nde_join_existing_vsphere.html"
    - title: Configure las credenciales de NetApp HCI
      url: "/docs/task_nde_configure_credentials.html"
    - title: Seleccione una topología de red
      url: "/docs/task_nde_select_net_topology.html"
    - title: Selección de inventario
      entries:
      - title: Selección de inventario y compatibilidad de nodos
        url: "/docs/concept_nde_node_compatibility.html"
      - title: Seleccione un inventario
        url: "/docs/task_nde_select_inventory.html"
    - title: Configure los ajustes de red
      url: "/docs/task_nde_configure_net_settings.html"
    - title: Revisión e implementación
      url: "/docs/task_nde_review_deploy.html"
    - title: Tareas posteriores a la implementación
      entries:
      - title: Información general de las tareas posteriores a la implementación
        url: "/docs/concept_nde_post_deployment_overview.html"
      - title: Cambios de red admitidos
        url: "/docs/task_nde_supported_net_changes.html"
      - title: Deshabilite el servicio smartd en los nodos de computación de NetApp
          HCI
        url: "/docs/task_nde_disable_smartd.html"
      - title: Deshabilite el comando "lacp-individual" en los switches configurados
        url: "/docs/task_nde_disable_lacp_individual.html"
      - title: Cree una función HCC de NetApp en vCenter
        url: "/docs/task_mnode_create_netapp_hcc_role_vcenter.html"
      - title: Mantenga actualizado VMware vSphere
        url: "/docs/task_nde_update_vsphere.html"
      - title: Instale los controladores de GPU para los nodos de computación habilitados
          para GPU
        url: "/docs/task_nde_install_GPU_drivers.html"
      - title: Acceda a Control del cloud híbrido de NetApp
        url: "/docs/task_nde_access_hcc.html"
      - title: Reduzca el desgaste de los medios de arranque en un nodo de computación
          NetApp HCI
        url: "/docs/task_reduce_boot_media_wear.html"
  - title: Gestione NetApp HCI
    entries:
    - title: Información general sobre Manage NetApp HCI
      url: "/docs/task_hci_manage_overview.html"
    - title: Configure el acceso completo a la interfaz de usuario web de Nombre de
        dominio
      url: "/docs/task_nde_access_ui_fqdn.html"
    - title: Cambiar las credenciales en NetApp HCI
      url: "/docs/task_post_deploy_credentials.html"
    - title: Actualice las credenciales de vCenter y ESXi
      url: "/docs/task_hci_credentials_vcenter_esxi.html"
    - title: Gestione el almacenamiento NetApp HCI
      entries:
      - title: Información general del almacenamiento de Manage NetApp HCI
        url: "/docs/task_hcc_manage_storage_overview.html"
      - title: Crear y administrar cuentas de usuario
        url: "/docs/task_hcc_manage_accounts.html"
      - title: Añadir y gestionar clústeres de almacenamiento
        url: "/docs/task_hcc_manage_storage_clusters.html"
      - title: Cree y gestione volúmenes
        url: "/docs/task_hcc_manage_vol_management.html"
      - title: Permite crear y gestionar grupos de acceso de volúmenes
        url: "/docs/task_hcc_manage_vol_access_groups.html"
      - title: Cree y gestione iniciadores
        url: "/docs/task_hcc_manage_initiators.html"
      - title: Cree y gestione políticas de calidad de servicio de volúmenes
        url: "/docs/task_hcc_qos_policies.html"
    - title: Trabaje con el nodo de gestión
      entries:
      - title: Información general sobre los nodos de gestión
        url: "/docs/task_mnode_work_overview.html"
      - title: Instale o recupere un nodo de gestión
        entries:
        - title: Instale un nodo de gestión
          url: "/docs/task_mnode_install.html"
        - title: Configurar una controladora de interfaz de red (NIC) de almacenamiento
          url: "/docs/task_mnode_install_add_storage_NIC.html"
        - title: Recupere un nodo de gestión
          url: "/docs/task_mnode_recover.html"
      - title: Acceda al nodo de gestión
        url: "/docs/task_mnode_access_ui.html"
      - title: Cambie el certificado SSL predeterminado del nodo de gestión
        url: "/docs/reference_change_mnode_default_ssl_certificate.html"
      - title: Trabaje con la interfaz de usuario del nodo de gestión
        entries:
        - title: Información general de la interfaz de usuario del nodo de gestión
          url: "/docs/task_mnode_work_overview_UI.html"
        - title: Configure la supervisión de alertas en NetApp HCI
          url: "/docs/task_mnode_enable_alerts.html"
        - title: Modifique y pruebe la red, el clúster y la configuración del sistema
            de los nodos de gestión
          url: "/docs/task_mnode_settings.html"
        - title: Ejecute las utilidades del sistema desde el nodo de gestión
          url: "/docs/task_mnode_run_system_utilities.html"
      - title: Trabaje con la API DE REST del nodo de gestión
        entries:
        - title: Información general de la interfaz de usuario de la API DE REST del
            nodo de
          url: "/docs/task_mnode_work_overview_API.html"
        - title: Obtenga autorización para utilizar las API de REST
          url: "/docs/task_mnode_api_get_authorizationtouse.html"
        - title: Habilite la supervisión de Active IQ y NetApp HCI
          url: "/docs/task_mnode_enable_activeIQ.html"
        - title: Configure Cloud Control de NetApp híbrido para varias instancias
            de vCenter
          url: "/docs/task_mnode_multi_vcenter_config.html"
        - title: Añada activos de computación y de controladora al nodo de gestión
          url: "/docs/task_mnode_add_assets.html"
        - title: Cómo localizar una etiqueta de hardware para un nodo de computación
          url: "/docs/task_mnode_locate_hardware_tag.html"
        - title: Crear y gestionar activos de clúster de almacenamiento
          url: "/docs/task_mnode_manage_storage_cluster_assets.html"
        - title: Ver o editar activos de controladora existentes
          url: "/docs/task_mnode_edit_vcenter_assets.html"
        - title: Quite un activo del nodo de gestión
          url: "/docs/task_mnode_remove_assets.html"
        - title: Configure un servidor proxy para el nodo de gestión
          url: "/docs/task_mnode_configure_proxy_server.html"
        - title: Verifique el sistema operativo del nodo de gestión y las versiones
            de servicios
          url: "/docs/task_mnode_api_find_mgmt_svcs_version.html"
        - title: Obtener registros de los servicios de gestión
          url: "/docs/task_mnode_logs.html"
      - title: Gestión de conexiones de soporte
        entries:
        - title: Inicie una sesión de soporte remota de NetApp
          url: "/docs/task_mnode_enable_remote_support_connections.html"
        - title: Gestione la funcionalidad SSH en el nodo de gestión
          url: "/docs/task_mnode_ssh_management.html"
    - title: Apaga o enciende el sistema NetApp HCI
      entries:
      - title: Descripción general de la alimentación de NetApp HCI
        url: "/docs/concept_nde_hci_power_off_on.html"
      - title: Apague los recursos informáticos de un sistema NetApp HCI
        url: "/docs/task_nde_hci_power_off_compute.html"
      - title: Apague los recursos de almacenamiento de un sistema NetApp HCI
        url: "/docs/task_nde_hci_power_off_storage.html"
      - title: Activar recursos de almacenamiento para un sistema NetApp HCI
        url: "/docs/task_nde_hci_power_on_storage.html"
      - title: Encienda los recursos informáticos para un sistema NetApp HCI
        url: "/docs/task_nde_hci_power_on_compute.html"
  - title: Supervise su sistema NetApp HCI con el control del cloud híbrido de NetApp
    entries:
    - title: Consulte los recursos en la consola de control del cloud híbrido de NetApp
      url: "/docs/task_hcc_dashboard.html"
    - title: Consulte su inventario en la página Nodes de NetApp Hybrid Cloud Control
      url: "/docs/task_hcc_nodes.html"
    - title: Edite la información de conexión de BMC con NetApp Hybrid Cloud Control
      url: "/docs/task_hcc_edit_bmc_info.html"
    - title: Supervise los volúmenes en su clúster de almacenamiento con Hybrid Cloud
        Control de NetApp
      url: "/docs/task_hcc_volumes.html"
    - title: Supervise el rendimiento, la capacidad y el estado del clúster con las
        conexiones de Cloud Control de NetApp híbrido a Active IQ
      url: "/docs/task_hcc_activeiq.html"
    - title: Recopile registros para solucionar problemas
      url: "/docs/task_hcc_collectlogs.html"
  - title: Actualice su sistema NetApp HCI versión 1.9 o 1.9P1
    entries:
    - title: Información general sobre la secuencia de actualización
      url: "/docs/concept_hci_upgrade_overview.html"
    - title: Procedimientos de actualización del sistema
      entries:
      - title: Actualice los servicios de gestión
        url: "/docs/task_hcc_update_management_services.html"
      - title: Actualice a la versión más reciente de HealthTools
        url: "/docs/task_upgrade_element_latest_healthtools.html"
      - title: Ejecute comprobaciones del estado del almacenamiento de Element antes
          de actualizar el almacenamiento
        url: "/docs/task_hcc_upgrade_element_prechecks.html"
      - title: Actualice el software Element
        url: "/docs/task_hcc_upgrade_element_software.html"
      - title: Actualizar el firmware de almacenamiento
        url: "/docs/task_hcc_upgrade_storage_firmware.html"
      - title: Actualice un nodo de gestión
        url: "/docs/task_hcc_upgrade_management_node.html"
      - title: Actualice el plugin de NetApp Element para vCenter Server
        url: "/docs/task_vcp_upgrade_plugin.html"
      - title: Ejecute comprobaciones de estado del nodo de computación antes de actualizar
          el firmware de computación
        url: "/docs/task_upgrade_compute_prechecks.html"
      - title: Actualice las controladoras del nodo de computación
        url: "/docs/task_hcc_upgrade_compute_node_drivers.html"
      - title: Actualizar el firmware del nodo de computación
        url: "/docs/task_hcc_upgrade_compute_node_firmware.html"
      - title: Automatice las actualizaciones de firmware de los nodos de computación
          con Ansible
        url: "/docs/task_hcc_upgrade_compute_firmware_ansible.html"
    - title: Actualice los componentes de vSphere para un sistema NetApp HCI con el
        plugin de Element para vCenter Server
      url: "/docs/task_hci_upgrade_all_vsphere.html"
  - title: Amplíe su sistema NetApp HCI
    entries:
    - title: Expandir información general
      url: "/docs/concept_hcc_expandoverview.html"
    - title: Amplíe los recursos de almacenamiento de NetApp HCI
      url: "/docs/task_hcc_expand_storage.html"
    - title: Amplíe los recursos de computación de NetApp HCI
      url: "/docs/task_hcc_expand_compute.html"
    - title: Amplíe los recursos informáticos y de almacenamiento de NetApp
      url: "/docs/task_hcc_expand_compute_and_storage.html"
    - title: Quite nodos de testigos después de expandir el clúster
      url: "/docs/task_hci_removewn.html"
  - title: Use Rancher en NetApp HCI
    entries:
    - title: Descripción general de rancher on NetApp HCI
      url: "/docs/concept_rancher_product_overview.html"
    - title: Conceptos
      url: "/docs/concept_rancher_concepts.html"
    - title: Requisitos para Rancher en NetApp HCI
      url: "/docs/rancher_prereqs_overview.html"
    - title: Ponga en marcha Rancher en NetApp HCI
      url: "/docs/task_rancher_deploy.html"
    - title: Tareas posteriores a la implementación
      entries:
      - title: Información general de las tareas posteriores a la implementación
        url: "/docs/concept_rancher_post_deployment_overview.html"
      - title: Asegúrese de que la paridad sea compatible con Rancher
        url: "/docs/task_rancher_ensure_rancher_support_parity.html"
      - title: Mejore la resiliencia de los equipos virtuales Rancher
        url: "/docs/task_rancher_config_anti_affinity.html"
      - title: Configurar la supervisión
        url: "/docs/task_rancher_enable_monitoring.html"
      - title: Instale Trident
        url: "/docs/task_rancher_trident.html"
      - title: Habilite la compatibilidad de Trident para clústeres de usuarios
        url: "/docs/task_trident_configure_networking.html"
    - title: Poner en marcha aplicaciones y clústeres de usuarios
      url: "/docs/task_rancher_deploy_user_clusters.html"
    - title: Administrar Rancher en NetApp HCI
      url: "/docs/task_rancher_manage.html"
    - title: Monitor Rancher en NetApp HCI
      url: "/docs/task_rancher_monitor.html"
    - title: Actualice Rancher en NetApp HCI
      url: "/docs/task_rancher_upgrades.html"
    - title: Retire una instalación de Rancher en NetApp HCI
      url: "/docs/task_rancher_remove_deployment.html"
  - title: Mantenimiento de hardware H-Series
    entries:
    - title: Descripción general del mantenimiento de hardware H-Series
      url: "/docs/task_hci_hwmainoverview.html"
    - title: Sustituya el chasis 2U de la serie H
      url: "/docs/task_hci_hserieschassisrepl.html"
    - title: Sustituya las unidades de alimentación CC en los nodos H615C y H610S
      url: "/docs/task_hci_dcpsurepl.html"
    - title: Reemplace los DIMM en los nodos de computación
      url: "/docs/task_hci_dimmcomputerepl.html"
    - title: Sustituya las unidades para los nodos de almacenamiento
      url: "/docs/task_hci_driverepl.html"
    - title: Sustituya los nodos H410C
      url: "/docs/task_hci_h410crepl.html"
    - title: Sustituya los nodos H410S
      url: "/docs/task_hci_h410srepl.html"
    - title: Reemplace los nodos H610C y H615C
      url: "/docs/task_hci_h610ch615crepl.html"
    - title: Sustituya los nodos H610S
      url: "/docs/task_hci_h610srepl.html"
    - title: Sustituya las unidades de alimentación
      url: "/docs/task_hci_psurepl.html"
    - title: Sustituir los interruptores SN2010, SN2100 y SN2700
      url: "/docs/task_hci_snswitches.html"
    - title: Sustituya el nodo de almacenamiento en un clúster de dos nodos
      url: "/docs/task_hci_2noderepl.html"
  - title: Versiones anteriores
    url: "/docs/reference_earlier_versions.html"
  - title: Avisos legales
    url: "/docs/reference_notices_hci.html"
