---
sidebar: sidebar 
permalink: docs/task_hci_credentials_vcenter_esxi.html 
summary: En una instalación de NetApp HCI, puede cambiar credenciales de vCenter y de los hosts ESXi para un nodo de computación gestionado por el control de cloud híbrido de NetApp. 
keywords: netapp, hci, password, credential, vcenter, esxi, hybrid cloud control 
---
= Actualice las credenciales de vCenter y ESXi
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Para mantener toda la funcionalidad del control del cloud híbrido de NetApp en su instalación de NetApp HCI, cuando cambia las credenciales en hosts vCenter y ESXi, también debe actualizar esas credenciales en el servicio de activos en el nodo de gestión.

.Acerca de esta tarea
El control de cloud híbrido de NetApp se comunica con vCenter y con los nodos de computación individuales que ejecutan VMware vSphere ESXi para recuperar información para la consola y facilitar actualizaciones graduales del firmware, el software y los controladores. Control de cloud híbrido de NetApp y sus servicios relacionados en el nodo de gestión utilizan credenciales (nombre de usuario/contraseña) para realizar la autenticación en VMware vCenter y ESXi.

Si la comunicación entre estos componentes falla, NetApp Hybrid Cloud Control y vCenter muestran mensajes de error cuando se producen problemas de autenticación. El control de cloud híbrido de NetApp muestra un banner de error rojo si no puede comunicarse con la instancia de VMware vCenter asociada en la instalación de NetApp HCI. VMware vCenter mostrará mensajes de bloqueo de cuenta ESXi para hosts ESXi individuales como resultado del control de cloud híbrido de NetApp con credenciales obsoletas.

El nodo de gestión en NetApp HCI hace referencia a estos componentes con los nombres siguientes:

* "Activos de controladora" son instancias de vCenter asociadas con la instalación de NetApp HCI.
* "Activos de nodos de computación" son los hosts ESXi en la instalación de NetApp HCI.


Durante la instalación inicial de NetApp HCI con el motor de puesta en marcha de NetApp, el nodo de gestión almacenaba las credenciales del usuario administrativo que especificó para vCenter y la contraseña de la cuenta "raíz" en los servidores ESXi.



== Actualice la contraseña de vCenter mediante la API DE REST de nodo de gestión

Siga los pasos para actualizar los activos de la controladora. Consulte link:task_mnode_edit_vcenter_assets.html["Ver o editar activos de controladora existentes"].



== Actualice la contraseña de ESXi mediante la API DE REST del nodo de gestión

.Pasos
. Para obtener información general de la interfaz de usuario de la API DE REST del nodo de gestión, consulte link:task_mnode_work_overview_API.html["Información general de la interfaz de usuario de la API DE REST del nodo de gestión"].
. Acceda a la interfaz de usuario de API DE REST para realizar servicios de gestión en el nodo de gestión:
+
[listing]
----
https://<ManagementNodeIP>/mnode
----
+
Sustituya <management node IP> por la dirección IPv4 del nodo de gestión en la red de gestión que utiliza NetApp HCI.

. Haga clic en *autorizar* o en cualquier icono de bloqueo y complete lo siguiente:
+
.. Introduzca el nombre de usuario y la contraseña de administración del clúster de SolidFire de NetApp.
.. Introduzca el ID de cliente as `mnode-client`.
.. Haga clic en *autorizar* para iniciar una sesión.
.. Cierre la ventana.


. En la interfaz de usuario DE LA API DE REST, haga clic en *GET ​/assets/Compute_Nodes*.
+
De esta forma, se recuperan los registros de activos de nodos de computación almacenados en el nodo de gestión.

+
Este es el enlace directo a esta API en la interfaz de usuario:

+
[listing]
----
https://<ManagementNodeIP>/mnode/#/assets/routes.v1.assets_api.get_compute_nodes
----
. Haga clic en *probar*.
. Haga clic en *Ejecutar*.
. En el cuerpo de respuesta, identifique los registros de activos del nodo de computación que necesitan credenciales actualizadas. Puede utilizar las propiedades “ip” y “host_name” para encontrar los registros de host ESXi correctos.
+
[listing]
----
"config": { },
"credentialid": <credential_id>,
"hardware_tag": <tag>,
"host_name": <host_name>,
"id": <id>,
"ip": <ip>,
"parent": <parent>,
"type": ESXi Host
----
+

NOTE: El paso siguiente utiliza los campos “padre” e “id” del registro de activos de cálculo para hacer referencia al registro que se va a actualizar.

. Configure el activo específico del nodo de computación:
+
.. Haga clic en *PUT /assets/{Asset_id}/compute-Nodes/{Compute_id}*.
+
Este es el enlace directo a la API en la interfaz de usuario:

+
[listing]
----
https://<ManagementNodeIP>/mnode/#/assets/routes.v1.assets_api.put_assets_compute_id
----
.. Haga clic en *probar*.
.. Introduzca “asset_id” con la información “parent”.
.. Introduzca “Compute_id” con la información “id”.
.. Modifique el cuerpo de la solicitud en la interfaz de usuario para actualizar sólo los parámetros de contraseña y nombre de usuario en el registro de activos de computación:
+
[listing]
----
{
"password": "<password>",
"username": "<username>"
}
----
.. Haga clic en *Ejecutar*.
.. Validar que la respuesta es HTTP 200, que indica que las nuevas credenciales se han almacenado en el registro de activos de cálculo de referencia


. Repita los dos pasos anteriores para obtener activos de nodos de computación adicionales que se deben actualizar con una contraseña nueva.
. Vaya a. https://<mNode_ip>/inventory/1/[].
+
.. Haga clic en *autorizar* o en cualquier icono de bloqueo y complete lo siguiente:
+
... Introduzca el nombre de usuario y la contraseña de administración del clúster de SolidFire de NetApp.
... Introduzca el ID de cliente as `mnode-client`.
... Haga clic en *autorizar* para iniciar una sesión.
... Cierre la ventana.


.. En la interfaz de usuario DE LA API DE REST, haga clic en *GET /Installations*.
.. Haga clic en *probar*.
.. Seleccione *Verdadero* en la lista desplegable Descripción de actualización.
.. Haga clic en *Ejecutar*.
.. Validar que la respuesta es HTTP 200.


. Espere aproximadamente 15 minutos para que desaparezca el mensaje de bloqueo de cuenta en vCenter.


[discrete]
== Obtenga más información

* https://docs.netapp.com/us-en/vcp/index.html["Plugin de NetApp Element para vCenter Server"^]
* https://www.netapp.com/hybrid-cloud/hci-documentation/["Página de recursos de NetApp HCI"^]

