---
sidebar: sidebar 
permalink: docs/task_hci_manage_overview.html 
summary: Es posible configurar el FQDM y administrar credenciales para NetApp HCI, cuentas de usuario, clústeres de almacenamiento, volúmenes, grupos de acceso de volúmenes, Los iniciadores, las políticas de calidad de servicio de los volúmenes y el nodo de gestión. 
keywords: netapp, hci, install, deploy, get started, configure, fqdn, fully qualified domain name 
---
= Información general de la gestión de NetApp HCI
:allow-uri-read: 


[role="lead"]
Es posible configurar el nombre de dominio completo y gestionar credenciales para NetApp HCI, cuentas de usuario, clústeres de almacenamiento, volúmenes, grupos de acceso de volúmenes, Los iniciadores, las políticas de calidad de servicio de los volúmenes y el nodo de gestión.

Estos son los elementos con los que puede trabajar:

* link:task_nde_access_ui_fqdn.html["Configure el acceso completo a la interfaz de usuario web de Nombre de dominio"]
* link:task_post_deploy_credentials.html["Cambiar las credenciales en NetApp HCI"]
* link:task_hci_credentials_vcenter_esxi.html["Actualice las credenciales de vCenter y ESXi"]
* link:task_hcc_manage_storage_overview.html["Gestione activos de almacenamiento de NetApp HCI"]
* link:task_mnode_work_overview.html["Trabaje con el nodo de gestión"]
* link:concept_nde_hci_power_off_on.html["Apaga o enciende el sistema NetApp HCI"]

