---
sidebar: sidebar 
permalink: docs/task_hcc_manage_storage_overview.html 
summary: Con NetApp HCI, puede gestionar activos de almacenamiento utilizando el control del cloud híbrido de NetApp. 
keywords: netapp, hci, on premise, cluster, element, account, user, volume, hybrid cloud control, hcc 
---
= Información general del almacenamiento de Manage NetApp HCI
:allow-uri-read: 


[role="lead"]
Con NetApp HCI, puede gestionar estos activos de almacenamiento utilizando el control del cloud híbrido de NetApp.

* link:task_hcc_manage_accounts.html["Crear y administrar cuentas de usuario"]
* link:task_hcc_manage_storage_clusters.html["Añadir y gestionar clústeres de almacenamiento"]
* link:task_hcc_manage_vol_management.html["Cree y gestione volúmenes"]
* link:task_hcc_manage_vol_access_groups.html["Permite crear y gestionar grupos de acceso de volúmenes"]
* link:task_hcc_manage_initiators.html["Cree y gestione iniciadores"]
* link:task_hcc_qos_policies.html["Cree y gestione políticas de calidad de servicio de volúmenes"]




== Obtenga más información

https://docs.netapp.com/us-en/vcp/index.html["Plugin de NetApp Element para vCenter Server"^]
